-- Seed data for EBS Contracts (generated from gestionContractos reference)
-- Perfiles: Equipos Basicos de Salud (ESE NORTE 3)

DELETE FROM ebs_actividades_perfil;
DELETE FROM ebs_perfiles;
DELETE FROM ebs_plantillas_observaciones;
ALTER SEQUENCE ebs_perfiles_id_seq RESTART WITH 1;
ALTER SEQUENCE ebs_actividades_perfil_id_seq RESTART WITH 1;
ALTER SEQUENCE ebs_plantillas_observaciones_id_seq RESTART WITH 1;

INSERT INTO ebs_perfiles (nombre, descripcion, honorario_referencia) VALUES ('MEDICINA', 'Profesional medico para atencion individual, familiar y comunitaria - Resolucion 3280 de 2018', 8000000);
INSERT INTO ebs_perfiles (nombre, descripcion, honorario_referencia) VALUES ('ENFERMERIA', 'Profesional de enfermeria para implementacion del PICP con enfasis materno-perinatal', 6500000);
INSERT INTO ebs_perfiles (nombre, descripcion, honorario_referencia) VALUES ('PSICOLOGIA', 'Profesional de psicologia para intervenciones colectivas en salud mental y psicosocial', 4500000);
INSERT INTO ebs_perfiles (nombre, descripcion, honorario_referencia) VALUES ('SALUD ORAL', 'Higienista oral para actividades de promocion y mantenimiento de salud bucal', 3000000);
INSERT INTO ebs_perfiles (nombre, descripcion, honorario_referencia) VALUES ('GESTOR COMUNITARIO', 'Gestor comunitario como enlace entre el equipo de salud y las comunidades', 2800000);
INSERT INTO ebs_perfiles (nombre, descripcion, honorario_referencia) VALUES ('AUXILIAR VACUNACION', 'Auxiliar de enfermeria para Programa Ampliado de Inmunizaciones (PAI)', 2500000);
INSERT INTO ebs_perfiles (nombre, descripcion, honorario_referencia) VALUES ('AUXILIAR ENFERMERIA', 'Auxiliar de enfermeria para apoyo a la gestion de Equipos Basicos de Salud', 2500000);

INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Realizar la identificación integral del riesgo individual, familiar y comunitario de la población adscrita al microterritorio asignado, considerando enfoques del PICP.', 1);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Ejecutar las atenciones individuales de promoción y mantenimiento de la salud, conforme a la Resolución 3280 de 2018 y lineamientos técnicos.', 2);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Aplicar las guías de práctica clínica, protocolos institucionales y lineamientos técnicos definidos por la E.S.E. NORTE 3.', 3);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Realizar acciones de inducción a la demanda de servicios de salud, priorizando eventos de salud pública.', 4);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Identificar, notificar y gestionar oportunamente los eventos de interés en salud pública.', 5);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Realizar la canalización oportuna de las personas a los servicios de salud del nivel primario o red de prestación.', 6);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Hacer seguimiento efectivo al acceso y continuidad de las atenciones en salud dentro de la red.', 7);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Promover espacios de concertación y mediación intercultural cuando aplique.', 8);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Promover y gestionar la articulación intersectorial y transectorial de los servicios de salud, sociales y ambientales.', 9);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Socializar con las comunidades atendidas los resultados de la caracterización familiar y del entorno.', 10);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Realizar la sistematización, registro y reporte de la información en los sistemas del Ministerio de Salud (PICP, canalización, seguimiento).', 11);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Identificar potencialidades, factores protectores y riesgos en los entornos para priorizar intervenciones.', 12);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Concertar y programar acciones sectoriales e intersectoriales enfocadas en la ejecución del PICP.', 13);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Participar en acciones de trabajo colaborativo, capacitación, cuidado al cuidador y seguimiento a la gestión del equipo.', 14);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Implementar las intervenciones colectivas concertadas en el PICP que correspondan al perfil médico.', 15);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Gestionar la garantía de las atenciones individuales en promoción, mantenimiento, detección temprana, diagnóstico y tratamiento.', 16);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Activar y gestionar los mecanismos de referencia y contrarreferencia.', 17);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Hacer uso adecuado de las Tecnologías de la Información y las Comunicaciones (TIC).', 18);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Diligenciar diaria, completa y oportunamente los Registros Individuales de Prestación de Servicios de Salud (RIPS) con códigos CIE-10.', 19);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Diligenciar de forma objetiva, clara y pertinente la historia clínica electrónica.', 20);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Cuando aplique, diligenciar la historia clínica física, garantizando legibilidad y completitud.', 21);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Educar a pacientes y familias sobre tratamientos, autocuidado y signos de alarma.', 22);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Hacer uso adecuado y responsable de los equipos, medicamentos, dispositivos e insumos.', 23);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Cumplir con las atenciones definidas para las familias beneficiarias según programación mensual.', 24);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Cumplir las normas de bioseguridad y seguridad del paciente.', 25);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Atender las orientaciones técnicas y de coordinación operativa del Coordinador EBS.', 26);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Cumplir con el plan de capacitaciones definido por la E.S.E. NORTE 3.', 27);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Registrar y validar las valoraciones médicas integrales acompañadas de educación en salud.', 28);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Contribuir al cumplimiento de las metas del programa con referencia al 100% de la población caracterizada.', 29);
-- [SKIPPED HTML TABLE] Actividad #30 for MEDICINA - too long for inline seed
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Participar en reuniones de seguimiento y evaluación de coordinación EBS.', 31);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Cumplir las actividades asistenciales propias del ejercicio profesional como médico general.', 32);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Acreditar afiliación y presentar pago de aportes a Seguridad Social Integral mensual.', 33);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Remitir oportunamente informes, cronogramas, soportes físicos y magnéticos requeridos.', 34);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Radicar la cuenta de cobro o factura con soportes exigidos.', 35);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Cumplir obligaciones aplicables de la Resolución 518 de 2015.', 36);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (1, 'Entregar soportes físicos y digitalizados de registros de atención y firmas.', 37);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Formular, implementar y realizar seguimiento al Plan Integral de Cuidado Primario (PICP) con énfasis materno-perinatal.', 1);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Identificar y analizar los riesgos individuales, familiares y comunitarios.', 2);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Brindar orientación e información clara sobre la oferta de servicios de salud.', 3);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Promover la afiliación al Sistema General de Seguridad Social en Salud.', 4);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Inducir a la demanda de servicios de salud y notificar eventos de interés en salud pública.', 5);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Realizar canalización oportuna a los servicios de nivel primario y red de prestación.', 6);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Hacer seguimiento al acceso efectivo y continuity de la atención.', 7);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Promover espacios de concertación y mediación intercultural.', 8);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Promover la articulación de los servicios de salud, sociales y ambientales.', 9);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Socializar los resultados de la caracterización con las comunidades.', 10);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Sistematizar, registrar y reportar la información en sistemas definidos por Minsalud.', 11);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Identificar potencialidades y riesgos en entornos para priorizar intervenciones.', 12);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Concertar y programar acciones sectoriales e intersectoriales para ejecutar el PICP.', 13);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Programar y participar en trabajo colaborativo, capacitación y cuidado al cuidador.', 14);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Implementar intervenciones del PICP que correspondan al perfil de enfermería.', 15);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Gestionar la asistencia social requerida por personas y familias con necesidades.', 16);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Activar los mecanismos de referencia y contrarreferencia.', 17);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Identificar y gestionar barreras de acceso (geográficas, culturales, económicas).', 18);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Diseñar y ejecutar estrategias de búsqueda activa y recuperación de inasistentes.', 19);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Realizar registro oportuno y completo de las intervenciones de enfermería.', 20);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Establecer estrategias de comunicación accesible e incluyente.', 21);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Realizar seguimiento y ajustes periódicos al PICP.', 22);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Revisar el avance de las acciones y metas del PICP y hacer ajustes.', 23);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Identificar oportunidades de mejora continua en la implementación del PICP.', 24);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Monitorear el cumplimiento de metas de cobertura poblacional.', 25);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Programar y participar en reuniones de retroalimentación comunitaria.', 26);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Aplicar guías de promoción, Resolución 3280, RIAS y guías de eventos de interés.', 27);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Hacer uso adecuado de las TIC.', 28);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Diligenciar los RIPS utilizando los códigos CIE-10.', 29);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Diligenciar la historia clínica electrónica de manera clara, objetiva y completa.', 30);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Diligenciar la historia clínica física cuando aplique.', 31);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Hacer uso adecuado de equipos, medicamentos, dispositivos e insumos.', 32);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Cumplir con la programación mensual informando ajustes.', 33);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Cumplir con atenciones de familias en microterritorios asignados.', 34);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Cumplir normas de bioseguridad y seguridad del paciente.', 35);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Participar en las reuniones de seguimiento del EBS.', 36);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Realizar registro y validación de valoraciones de enfermería respaldadas por educación.', 37);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Contribuir al cumplimiento de metas del 100% de la población caracterizada.', 38);
-- [SKIPPED HTML TABLE] Actividad #39 for ENFERMERIA - too long for inline seed
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Contribuir a la operatividad y articulación del EBS.', 40);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Cumplir con los lineamientos de capacitación definidos.', 41);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (2, 'Acreditar Seguridad Social, presentar informes de ejecución, atender requerimientos del supervisor, custodiar equipos, abstenerse de usar recursos institucionales a otros fines y garantizar confidencialidad de la historia clínica.', 42);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Ejecutar intervenciones colectivas en salud mental y psicosocial (redes comunitarias, centros de escucha).', 1);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Participar en la formulación, implementación y seguimiento del PICP con intervenciones en salud mental.', 2);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Identificar y analizar los riesgos psicosociales individuales, familiares y comunitarios.', 3);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Brindar orientación psicosocial e información clara sobre oferta de servicios en salud mental.', 4);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Inducir a la demanda de servicios de salud mental priorizando eventos de salud pública.', 5);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Realizar canalización oportuna a los servicios de salud primaria en salud mental.', 6);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Hacer seguimiento al acceso efectivo y continuidad de la atención psicosocial.', 7);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Promover espacios de conciliación, mediación y abordaje intercultural.', 8);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Promover y gestionar la articulación intersectorial con servicios sociales y educativos.', 9);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Socializar con las comunidades los resultados de la caracterización psicosocial.', 10);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Sistematizar, registrar y reportar la información en los registros definidos.', 11);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Identificar potencialidades, factores protectores y riesgos psicosociales del entorno.', 12);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Concertar y programar acciones sectoriales enfocadas en intervenciones psicosociales.', 13);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Programar y participar en acciones de trabajo colaborativo y cuidado al cuidador.', 14);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Implementar intervenciones colectivas psicosociales y gestionar atenciones individuales.', 15);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Gestionar la asistencia psicosocial requerida en articulación con el territorio.', 16);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Activar mecanismos de referencia y contrarreferencia en salud mental.', 17);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Identificar y gestionar barreras de acceso a la atención psicosocial.', 18);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Diseñar estrategias de búsqueda activa y recuperación de personas en salud mental.', 19);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Participar en reuniones de análisis de casos y cuidado al cuidador del equipo.', 20);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Registrar oportuna y completamente la información de intervenciones psicosociales.', 21);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Establecer mecanismos de comunicación accesible e incluyente.', 22);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Utilizar adecuadamente las TIC.', 23);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Diligenciar los RIPS utilizando códigos CIE-10.', 24);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Diligenciar de manera clara y pertinente la historia clínica electrónica.', 25);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Diligenciar la historia clínica física cuando aplique.', 26);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Hacer uso adecuado de equipos, herramientas e insumos.', 27);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Cumplir con la programación informando ajustes.', 28);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Cumplir con atenciones de familias en microterritorios.', 29);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Cumplir con normas de bioseguridad.', 30);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Participar en reuniones de seguimiento de coordinación EBS.', 31);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Acatar lineamientos técnicos y operativos del Coordinador EBS.', 32);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Realizar registro de valoraciones psicosociales respaldadas por educación en salud mental (Res 3280).', 33);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Contribuir al cumplimiento de metas 100%: Consulta psicología, aplicación tamizajes SPA, escala sobrecarga cuidador, atención a víctimas conflicto.', 34);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Realizar un total de 500 atenciones individuales mensuales en el marco de Promoción y Mantenimiento.', 35);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Diligenciar tamizajes en software institucional y plantilla de Minsalud.', 36);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (3, 'Cumplir con el plan de capacitaciones de Minsalud y E.S.E. NORTE 3.', 37);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Ejecutar actividades de higiene oral y promoción de salud bucal (Resolución 3280).', 1);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Diligenciar de manera oportuna los RIPS con códigos CIE-10.', 2);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Registrar de forma clara la información en la historia clínica electrónica.', 3);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Diligenciar la historia clínica física cuando aplique.', 4);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Brindar orientación sobre oferta de servicios de salud oral.', 5);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Apoyar promoción de afiliación a Seguridad Social.', 6);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Canalizar a las personas hacia servicios de salud oral bajo orientación del odontólogo.', 7);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Desarrollar actividades de demanda inducida comunitaria en salud oral.', 8);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Ejecutar acciones de búsqueda activa y seguimiento de salud bucal.', 9);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Apoyar la implementación de intervenciones colectivas del PICP en salud oral.', 10);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Articular con servicios sociales acciones de apoyo para usuarios.', 11);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Identificar riesgos en entornos para priorización de intervenciones orales.', 12);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Apoyar la logística de las actividades del EBS.', 13);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Apoyar seguimiento y ajuste de los PICP desde componente bucal.', 14);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Contribuir al cumplimiento de metas de cobertura.', 15);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Utilizar de manera adecuada las TIC.', 16);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Cumplir normas de bioseguridad en salud oral.', 17);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Participar en las reuniones de seguimiento y evaluación del EBS.', 18);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Aplicar lineamientos técnicos del odontólogo y Coordinador EBS.', 19);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Acreditar pago a Seguridad Social Integral.', 20);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Presentar oportunamente documentación para seguimiento contractual.', 21);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Radicar cuenta de cobro o factura en plazos establecidos.', 22);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Asistir a jornadas de capacitación de la E.S.E. o Minsalud.', 23);
-- [SKIPPED HTML TABLE] Actividad #24 for SALUD ORAL - too long for inline seed
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Desarrollar actividades educativas comunitarias (charlas, talleres).', 25);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (4, 'Brindar apoyo en atención inicial de urgencia odontológica y canalizar.', 26);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Participar en la priorización de los microterritorios del municipio asignado.', 1);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Apoyar la elaboración de cartografía social de los microterritorios priorizados.', 2);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Actuar como enlace comunitario entre el Equipo de Salud Territorial (EST) y las comunidades.', 3);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Apoyar el relacionamiento inicial entre el EST y la comunidad, promoviendo confianza.', 4);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Contribuir al análisis de los determinantes sociales aportando información del contexto.', 5);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Identificar tempranamente situaciones de riesgo a nivel individual y canalizar al equipo.', 6);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Fortalecer actividades de información y educación de la población hacia servicios de salud.', 7);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Apoyar el seguimiento familiar a las acciones definidas en el PICP.', 8);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Contribuir al diseño de estrategias de comunicación accesible e incluyente.', 9);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Apoyar el seguimiento y ajuste de los PICP de acuerdo con resultados comunitarios.', 10);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Apoyar la revisión del avance de metas establecidas en los PICP.', 11);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Contribuir al seguimiento de metas de cobertura en la población asignada.', 12);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Participar en las reuniones de retroalimentación comunitaria.', 13);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Gestionar asistencia social requerida por personas con necesidades, articulando con el territorio.', 14);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Identificar potencialidades y riesgos en los entornos comunitarios.', 15);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Apoyar la programación, planeación y logística de actividades del componente comunitario.', 16);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Participar en reuniones de seguimiento y evaluación de coordinación EBS.', 17);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Ejecutar actividades propias del rol relacionadas con Atención Primaria en Salud.', 18);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Acreditar afiliación y pago de Seguridad Social Integral.', 19);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Remitir informes, cronogramas y documentos requeridos por la supervisión.', 20);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Radicar cuenta de cobro al finalizar la ejecución.', 21);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Cumplir con disposiciones de la Resolución 518 de 2015 en salud pública.', 22);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Entregar soportes físicos y digitales de registros de firmas y acciones.', 23);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (5, 'Actuar conforme a lineamientos técnicos y operativos del programa EBS.', 24);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Ejecutar actividades como Auxiliar de Enfermería según lineamientos del MIAS y APS.', 1);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Realizar la identificación de riesgos y necesidades de la población asignada (Res 3280).', 2);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Registrar la información de identificación de riesgos en instrumentos de la E.S.E.', 3);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Promover la afiliación de la población a Seguridad Social en Salud.', 4);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Apoyar la canalización de usuarios hacia la red de prestación primaria.', 5);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Ejecutar acciones de demanda inducida comunitaria y búsqueda activa.', 6);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Apoyar la implementación de intervenciones del PICP a cargo del Equipo de Salud.', 7);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Articular con servicios sociales acciones de asistencia para personas con necesidades.', 8);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Identificar riesgos en entornos para priorizar intervenciones.', 9);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Apoyar la logística de las salidas extramurales a los microterritorios.', 10);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Apoyar la planeación y desarrollo de actividades logísticas del EBS.', 11);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Apoyar el registro de intervenciones en los RIPS con códigos CIE-10.', 12);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Apoyar el seguimiento al diligenciamiento de historias clínicas y formatos.', 13);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Desarrollar actividades de educación para la salud dirigidas a la población.', 14);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Utilizar adecuadamente las TIC en actividades asistenciales y registro.', 15);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Custodiar, conservar y hacer uso adecuado de equipos e insumos.', 16);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Hacer uso responsable de medicamentos conforme a protocolos.', 17);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Cumplir con normas de bioseguridad del Manual de la E.S.E.', 18);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Participar en las jornadas de capacitación y actualización de Minsalud/E.S.E.', 19);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Presentar informes periódicos de actividades objetivas y verificables.', 20);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Acreditar pago de Seguridad Social Integral y presentar soportes.', 21);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Radicar cuenta de cobro de manera mensual con soportes requeridos.', 22);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (6, 'Apoyar la identificación de riesgos aplicando instrumentos definidos por la E.S.E.', 23);
-- [SKIPPED HTML TABLE] Actividad #24 for AUXILIAR VACUNACION - too long for inline seed
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Ejecutar actividades propias de Auxiliar de Enfermería según lineamientos MIAS y APS.', 1);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Realizar la identificación de riesgos y necesidades de la población (Res 3280).', 2);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Registrar información derivada de la identificación de riesgos en instrumentos.', 3);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Promover la afiliación de la población a Seguridad Social en Salud.', 4);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Apoyar la canalización de usuarios hacia la red de nivel primario.', 5);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Ejecutar acciones de demanda inducida comunitaria, búsqueda activa y control.', 6);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Apoyar la implementación de intervenciones del PICP a cargo del EBS.', 7);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Articular con servicios sociales acciones dirigidas a personas con necesidades.', 8);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Identificar riesgos y potencialidades en los entornos sociosanitarios.', 9);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Apoyar logística de salidas extramurales a territorios y microterritorios.', 10);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Apoyar la planeación y desarrollo logístico de actividades del EBS.', 11);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Apoyar el registro de intervenciones en registros administrativos (RIPS).', 12);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Apoyar seguimiento al diligenciamiento de historias clínicas y formatos.', 13);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Desarrollar actividades de educación para la salud según contexto sociocultural.', 14);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Utilizar adecuadamente las TIC.', 15);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Custodiar equipos, herramientas, insumos y bienes entregados para ejecución.', 16);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Hacer uso responsable de medicamentos, dispositivos médicos e insumos.', 17);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Cumplir normas de bioseguridad según manual adoptado por E.S.E.', 18);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Participar en jornadas de capacitación de la E.S.E. o Ministerio de Salud.', 19);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Presentar informes periódicos de actividades objetivas y verificables.', 20);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Acreditar pago a Seguridad Social Integral.', 21);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Radicar cuenta de cobro mensual con soportes correspondientes.', 22);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Apoyar identificación de riesgos y necesidades mediante aplicación de instrumentos.', 23);
INSERT INTO ebs_actividades_perfil (perfil_id, descripcion, orden) VALUES (7, 'Cumplir como mínimo con metas de identificación mensual: 210 formularios de familias o 483 personas caracterizadas.', 24);

INSERT INTO ebs_plantillas_observaciones (titulo, contenido) VALUES ('CUMPLIMIENTO TOTAL (SIN DESCUENTO)', 'Una vez verificado el informe de actividades, los soportes allegados y demás evidencias presentadas por el CONTRATISTA, se constata el cumplimiento de las obligaciones contractuales correspondientes al periodo evaluado, conforme a lo establecido en el contrato. En consecuencia, desde la supervisión se conceptúa favorablemente el cumplimiento de las actividades desarrolladas y se autoriza el trámite de pago de la cuenta de cobro presentada, por encontrarse debidamente soportada. No obstante, se recomienda al CONTRATISTA mantener vigente su afiliación a las administradoras del Sistema General de Seguridad Social Integral, así como continuar efectuando de manera oportuna los aportes correspondientes, en cumplimiento de la normativa vigente aplicable y de las obligaciones contractuales asumidas, mínimo, mientras se encuentre vigente el contrato.');
INSERT INTO ebs_plantillas_observaciones (titulo, contenido) VALUES ('CUMPLIMIENTO PARCIAL (CON DESCUENTO)', 'Verificado lo informes de actividades, los soportes allegados y demás evidencias presentadas por el CONTRATISTA, se evidencia un cumplimiento parcial de las obligaciones contractuales correspondientes al periodo evaluado, conforme a lo establecido en el contrato y en el plan de actividades aprobado. Se deja constancia de que no se ejecutó la totalidad de las actividades previstas, situación que se encuentra debidamente soportada en la verificación realizada por la supervisión. En consecuencia, y en aplicación del principio de pago contra prestación efectivamente ejecutada, así como de lo pactado en el contrato, la supervisión determina el reconocimiento y pago únicamente de las actividades efectivamente desarrolladas y soportadas, procediendo al ajuste del valor de la cuenta de cobro en proporción a dicho cumplimiento. Por lo anterior, se autoriza el trámite de pago por el valor ajustado, conforme a la verificación efectuada. Finalmente, se recomienda al CONTRATISTA mantener vigente su afiliación al Sistema General de Seguridad Social Integral y efectuar oportunamente los aportes correspondientes, en cumplimiento de la normativa vigente y de las obligaciones contractuales asumidas.');
INSERT INTO ebs_plantillas_observaciones (titulo, contenido) VALUES ('RECUPERACION DE DESCUENTO', 'Verificado el informe de actividades, los soportes allegados y demás evidencias presentadas por el CONTRATISTA, se evidencia que durante el periodo evaluado se ejecutaron actividades adicionales y/o se subsanaron aquellas que dieron lugar a la aplicación de un descuento en periodos anteriores, dentro del mismo término de ejecución contractual. En ese sentido, la supervisión constata que las actividades previamente no reconocidas fueron efectivamente desarrolladas y debidamente soportadas, cumpliendo con las condiciones técnicas y contractuales exigidas. En consecuencia, y en aplicación del principio de reconocimiento de la prestación efectivamente ejecutada, se autoriza la recuperación del valor descontado, en proporción a las actividades verificadas, procediendo su inclusión en el trámite de pago correspondiente al presente periodo. Lo anterior se realiza sin que ello implique modificación de las condiciones contractuales, sino en garantía del equilibrio contractual y del pago justo por las actividades efectivamente ejecutadas y acreditadas.');
