--
-- PostgreSQL database dump
--

\restrict wa9yUNddJEMKxvYskzuBkxgjdpPscav8NoUtFz3ecQeDvuaIihpZ4pmLogIlT9P

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointment_notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointment_notifications (
    id integer NOT NULL,
    appointment_id bigint NOT NULL,
    channel character varying(20) NOT NULL,
    type character varying(20) NOT NULL,
    recipient character varying(100) NOT NULL,
    message text,
    sent_at character varying(30),
    delivered_at character varying(30),
    status character varying(20),
    error_message text
);


ALTER TABLE public.appointment_notifications OWNER TO postgres;

--
-- Name: appointment_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.appointment_notifications_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.appointment_notifications_id_seq OWNER TO postgres;

--
-- Name: appointment_notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.appointment_notifications_id_seq OWNED BY public.appointment_notifications.id;


--
-- Name: appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments (
    id integer NOT NULL,
    patient_id bigint NOT NULL,
    professional_id bigint NOT NULL,
    agenda_id bigint NOT NULL,
    headquarters_id bigint NOT NULL,
    office_id bigint,
    date character varying(10) NOT NULL,
    start_time character varying(5) NOT NULL,
    end_time character varying(5),
    modality character varying(20) NOT NULL,
    functionality character varying(50) NOT NULL,
    service_type_id bigint NOT NULL,
    label character varying(255),
    administrative_notes text,
    clinical_notes text,
    status character varying(20) NOT NULL,
    auto_notification_enabled boolean DEFAULT false,
    is_group_session boolean DEFAULT false,
    created_at character varying(30),
    updated_at character varying(30),
    created_by bigint,
    confirmed_at character varying(30),
    confirmed_by bigint,
    cancelled_at character varying(30),
    cancelled_by bigint,
    cancellation_reason text
);


ALTER TABLE public.appointments OWNER TO postgres;

--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.appointments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.appointments_id_seq OWNER TO postgres;

--
-- Name: appointments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.appointments_id_seq OWNED BY public.appointments.id;


--
-- Name: attribute_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attribute_employee (
    id integer NOT NULL,
    employee_id integer,
    name_attribute character varying(100) NOT NULL,
    multiple boolean DEFAULT false
);


ALTER TABLE public.attribute_employee OWNER TO postgres;

--
-- Name: attribute_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attribute_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attribute_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attribute_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attribute_user (
    id integer NOT NULL,
    user_id integer,
    name_attribute character varying(100) NOT NULL,
    multiple boolean DEFAULT false
);


ALTER TABLE public.attribute_user OWNER TO postgres;

--
-- Name: attribute_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attribute_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attribute_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calendar_exception; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.calendar_exception (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    modality character varying(20) NOT NULL,
    headquarters_id bigint,
    office_id bigint,
    exception_date date NOT NULL,
    start_time character varying(5),
    end_time character varying(5),
    is_full_day boolean DEFAULT false,
    reason text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.calendar_exception OWNER TO postgres;

--
-- Name: calendar_exception_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.calendar_exception ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_exception_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contratos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contratos (
    id integer NOT NULL,
    eapb_id integer NOT NULL,
    nombre_contrato character varying(255) NOT NULL,
    regimen character varying(20) NOT NULL,
    modalidad_pago character varying(20) NOT NULL,
    objeto_contrato text NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    valor_total numeric(18,2) DEFAULT 0,
    estado character varying(20) DEFAULT 'BORRADOR'::character varying NOT NULL,
    nivel_complejidad character varying(20) NOT NULL,
    id_contrato_legal character varying(50),
    servicios_cubiertos text[] NOT NULL,
    sedes_aplicables integer[] NOT NULL,
    observaciones text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contratos_estado_check CHECK (((estado)::text = ANY ((ARRAY['BORRADOR'::character varying, 'ACTIVO'::character varying, 'VENCIDO'::character varying, 'INACTIVO'::character varying, 'SUSPENDIDO'::character varying])::text[]))),
    CONSTRAINT contratos_modalidad_pago_check CHECK (((modalidad_pago)::text = ANY ((ARRAY['CAPITACION'::character varying, 'EVENTO'::character varying, 'PGP'::character varying])::text[]))),
    CONSTRAINT contratos_nivel_complejidad_check CHECK (((nivel_complejidad)::text = ANY ((ARRAY['BAJA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying])::text[]))),
    CONSTRAINT contratos_regimen_check CHECK (((regimen)::text = ANY ((ARRAY['CONTRIBUTIVO'::character varying, 'SUBSIDIADO'::character varying, 'ESPECIAL'::character varying])::text[]))),
    CONSTRAINT fecha_fin_posterior CHECK ((fecha_fin > fecha_inicio))
);


ALTER TABLE public.contratos OWNER TO postgres;

--
-- Name: contratos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.contratos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.contratos_id_seq OWNER TO postgres;

--
-- Name: contratos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.contratos_id_seq OWNED BY public.contratos.id;


--
-- Name: departamentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamentos (
    id integer NOT NULL,
    nombre character varying(255) NOT NULL,
    codigo character varying(10) NOT NULL
);


ALTER TABLE public.departamentos OWNER TO postgres;

--
-- Name: departamentos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.departamentos_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.departamentos_id_seq OWNER TO postgres;

--
-- Name: departamentos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.departamentos_id_seq OWNED BY public.departamentos.id;


--
-- Name: eapbs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eapbs (
    id integer NOT NULL,
    nombre character varying(255) NOT NULL,
    nit character varying(9) NOT NULL,
    digito_verificacion character(1) NOT NULL,
    codigo_supersalud character varying(20) NOT NULL,
    regimen character varying(20) NOT NULL,
    naturaleza character varying(20) NOT NULL,
    estado character varying(20) DEFAULT 'ACTIVA'::character varying NOT NULL,
    representante_legal character varying(255),
    departamento_id integer NOT NULL,
    municipio_id integer NOT NULL,
    direccion character varying(255) NOT NULL,
    telefono character varying(50) NOT NULL,
    correo_electronico character varying(255) NOT NULL,
    id_interno_ese character varying(50),
    observaciones text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT eapbs_estado_check CHECK (((estado)::text = ANY ((ARRAY['ACTIVA'::character varying, 'INACTIVA'::character varying, 'EN_REVISION'::character varying, 'LIQUIDADA'::character varying])::text[]))),
    CONSTRAINT eapbs_naturaleza_check CHECK (((naturaleza)::text = ANY ((ARRAY['PUBLICA'::character varying, 'PRIVADA'::character varying, 'MIXTA'::character varying])::text[]))),
    CONSTRAINT eapbs_regimen_check CHECK (((regimen)::text = ANY ((ARRAY['CONTRIBUTIVO'::character varying, 'SUBSIDIADO'::character varying, 'ESPECIAL'::character varying])::text[])))
);


ALTER TABLE public.eapbs OWNER TO postgres;

--
-- Name: eapbs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.eapbs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.eapbs_id_seq OWNER TO postgres;

--
-- Name: eapbs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.eapbs_id_seq OWNED BY public.eapbs.id;


--
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id integer NOT NULL,
    names character varying(100) NOT NULL,
    lastnames character varying(100) NOT NULL,
    identification_type character varying(2) NOT NULL,
    identification_number character varying(15) NOT NULL,
    password character varying(255),
    rol_id integer,
    secret character varying(255)
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fb_attribute; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fb_attribute (
    id bigint NOT NULL,
    code character varying(100) NOT NULL,
    label character varying(255) NOT NULL,
    input_type character varying(30) NOT NULL,
    is_required boolean DEFAULT false NOT NULL,
    placeholder character varying(255),
    default_value character varying(500),
    tooltip character varying(500),
    validation_rules jsonb,
    options jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.fb_attribute OWNER TO postgres;

--
-- Name: fb_attribute_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fb_attribute_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fb_attribute_id_seq OWNER TO postgres;

--
-- Name: fb_attribute_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fb_attribute_id_seq OWNED BY public.fb_attribute.id;


--
-- Name: fb_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fb_template (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    is_active boolean DEFAULT true NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.fb_template OWNER TO postgres;

--
-- Name: fb_template_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fb_template_group (
    id bigint NOT NULL,
    template_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    sort_order integer DEFAULT 0 NOT NULL,
    icon character varying(50),
    is_collapsible boolean DEFAULT true NOT NULL
);


ALTER TABLE public.fb_template_group OWNER TO postgres;

--
-- Name: fb_template_group_attr; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fb_template_group_attr (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    attribute_id bigint NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    is_required_override boolean,
    label_override character varying(255),
    width character varying(10) DEFAULT 'full'::character varying NOT NULL
);


ALTER TABLE public.fb_template_group_attr OWNER TO postgres;

--
-- Name: fb_template_group_attr_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fb_template_group_attr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fb_template_group_attr_id_seq OWNER TO postgres;

--
-- Name: fb_template_group_attr_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fb_template_group_attr_id_seq OWNED BY public.fb_template_group_attr.id;


--
-- Name: fb_template_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fb_template_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fb_template_group_id_seq OWNER TO postgres;

--
-- Name: fb_template_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fb_template_group_id_seq OWNED BY public.fb_template_group.id;


--
-- Name: fb_template_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fb_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fb_template_id_seq OWNER TO postgres;

--
-- Name: fb_template_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.fb_template_id_seq OWNED BY public.fb_template.id;


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO postgres;

--
-- Name: medical_agenda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medical_agenda (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    modality character varying(20) NOT NULL,
    headquarters_id bigint,
    office_id bigint,
    start_date date NOT NULL,
    end_date date NOT NULL,
    work_days character varying(32) NOT NULL,
    start_time character varying(5) NOT NULL,
    end_time character varying(5) NOT NULL,
    appointment_duration integer NOT NULL,
    service_types text,
    allow_group_session boolean DEFAULT false,
    requires_referral boolean DEFAULT false,
    notes text,
    status character varying(24) DEFAULT 'VIGENTE'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    enabled boolean DEFAULT true,
    convenios text,
    can_create_medical_history boolean DEFAULT false,
    double_shift boolean DEFAULT false,
    enabled_slots integer,
    agenda_state character varying(20) DEFAULT 'ABIERTA'::character varying,
    frequency character varying(50),
    created_by character varying(100)
);


ALTER TABLE public.medical_agenda OWNER TO postgres;

--
-- Name: medical_agenda_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medical_agenda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_agenda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: municipios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.municipios (
    id integer NOT NULL,
    nombre character varying(255) NOT NULL,
    codigo character varying(10) NOT NULL,
    departamento_id integer NOT NULL
);


ALTER TABLE public.municipios OWNER TO postgres;

--
-- Name: municipios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.municipios_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.municipios_id_seq OWNER TO postgres;

--
-- Name: municipios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.municipios_id_seq OWNED BY public.municipios.id;


--
-- Name: permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permission (
    id integer NOT NULL,
    rol_id integer NOT NULL,
    method character varying(6) NOT NULL,
    endpoint character varying(50) NOT NULL
);


ALTER TABLE public.permission OWNER TO postgres;

--
-- Name: permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    asistencial boolean DEFAULT true
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedule (
    id bigint NOT NULL,
    employee_id bigint NOT NULL,
    user_id bigint NOT NULL,
    start_at timestamp without time zone NOT NULL,
    end_at timestamp without time zone NOT NULL,
    details text,
    group_session boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    headquarters character varying(100),
    office character varying(100),
    in_person boolean DEFAULT false,
    office_id bigint,
    agenda_id bigint
);


ALTER TABLE public.schedule OWNER TO postgres;

--
-- Name: schedule_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedule_config (
    id bigint NOT NULL,
    config_type character varying(50) NOT NULL,
    holiday_date date,
    description character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.schedule_config OWNER TO postgres;

--
-- Name: schedule_config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.schedule_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.schedule_config_id_seq OWNER TO postgres;

--
-- Name: schedule_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.schedule_config_id_seq OWNED BY public.schedule_config.id;


--
-- Name: schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session (
    id integer NOT NULL,
    user_id integer NOT NULL,
    token character varying(300) NOT NULL,
    ip_address character varying(100) NOT NULL,
    useragent character varying(2) NOT NULL,
    created_at character varying(15) NOT NULL,
    expiration character varying(15) NOT NULL
);


ALTER TABLE public.session OWNER TO postgres;

--
-- Name: session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tracking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tracking (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    employee_id bigint,
    action character varying(500) DEFAULT 'endpoint called'::character varying NOT NULL,
    data text,
    result text
);


ALTER TABLE public.tracking OWNER TO postgres;

--
-- Name: tracking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tracking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    names character varying(100) NOT NULL,
    lastnames character varying(100) NOT NULL,
    identification_type character varying(2) NOT NULL,
    identification_number character varying(15) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: value_attribute_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.value_attribute_employee (
    id integer NOT NULL,
    attribute_id integer,
    value_attribute character varying(100) NOT NULL
);


ALTER TABLE public.value_attribute_employee OWNER TO postgres;

--
-- Name: value_attribute_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.value_attribute_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.value_attribute_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: value_attribute_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.value_attribute_user (
    id integer NOT NULL,
    attribute_id integer,
    value_attribute character varying(100) NOT NULL
);


ALTER TABLE public.value_attribute_user OWNER TO postgres;

--
-- Name: value_attribute_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.value_attribute_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.value_attribute_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointment_notifications id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment_notifications ALTER COLUMN id SET DEFAULT nextval('public.appointment_notifications_id_seq'::regclass);


--
-- Name: appointments id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments ALTER COLUMN id SET DEFAULT nextval('public.appointments_id_seq'::regclass);


--
-- Name: contratos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contratos ALTER COLUMN id SET DEFAULT nextval('public.contratos_id_seq'::regclass);


--
-- Name: departamentos id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos ALTER COLUMN id SET DEFAULT nextval('public.departamentos_id_seq'::regclass);


--
-- Name: eapbs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eapbs ALTER COLUMN id SET DEFAULT nextval('public.eapbs_id_seq'::regclass);


--
-- Name: fb_attribute id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_attribute ALTER COLUMN id SET DEFAULT nextval('public.fb_attribute_id_seq'::regclass);


--
-- Name: fb_template id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template ALTER COLUMN id SET DEFAULT nextval('public.fb_template_id_seq'::regclass);


--
-- Name: fb_template_group id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group ALTER COLUMN id SET DEFAULT nextval('public.fb_template_group_id_seq'::regclass);


--
-- Name: fb_template_group_attr id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group_attr ALTER COLUMN id SET DEFAULT nextval('public.fb_template_group_attr_id_seq'::regclass);


--
-- Name: municipios id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipios ALTER COLUMN id SET DEFAULT nextval('public.municipios_id_seq'::regclass);


--
-- Name: schedule_config id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedule_config ALTER COLUMN id SET DEFAULT nextval('public.schedule_config_id_seq'::regclass);


--
-- Data for Name: appointment_notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointment_notifications (id, appointment_id, channel, type, recipient, message, sent_at, delivered_at, status, error_message) FROM stdin;
\.


--
-- Data for Name: appointments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments (id, patient_id, professional_id, agenda_id, headquarters_id, office_id, date, start_time, end_time, modality, functionality, service_type_id, label, administrative_notes, clinical_notes, status, auto_notification_enabled, is_group_session, created_at, updated_at, created_by, confirmed_at, confirmed_by, cancelled_at, cancelled_by, cancellation_reason) FROM stdin;
1	7	101	1	1	\N	2026-02-07	08:00	08:20	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-02-03T23:12:27.285433106	2026-02-03T23:12:27.285433106	0	\N	\N	\N	\N	\N
2	7	7	5	1	\N	2026-02-07	08:00	08:20	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Seguimiento		\N	PROGRAMADA	t	f	2026-02-03T23:29:02.990229849	2026-02-03T23:29:02.990229849	0	\N	\N	\N	\N	\N
3	7	7	15	1	\N	2026-06-18	08:20	08:40	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-02-25T00:41:05.927108464	2026-02-25T00:41:05.927108464	0	\N	\N	\N	\N	\N
4	7	7	9	1	\N	2026-03-09	08:20	08:40	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-02T21:58:06.129680305	2026-03-02T21:58:06.129680305	0	\N	\N	\N	\N	\N
5	1	7	9	1	\N	2026-03-07	08:20	08:40	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-02T22:01:06.066231946	2026-03-02T22:01:06.066231946	0	\N	\N	\N	\N	\N
6	2	1	17	1	\N	2026-03-07	08:00	08:20	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-02T22:31:40.957739581	2026-03-02T22:31:40.957739581	0	\N	\N	\N	\N	\N
7	1	13	18	1	\N	2026-03-19	08:20	08:40	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	t	2026-03-16T20:40:02.801796542	2026-03-16T20:40:02.801796542	0	\N	\N	\N	\N	\N
8	1	13	18	1	\N	2026-03-19	08:40	09:00	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	t	2026-03-16T20:40:20.491556218	2026-03-16T20:40:20.491556218	0	\N	\N	\N	\N	\N
9	6	13	18	1	\N	2026-03-20	08:20	08:40	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-16T20:54:08.693784683	2026-03-16T20:54:08.693784683	0	\N	\N	\N	\N	\N
10	1	13	18	1	\N	2026-03-17	13:40	14:00	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-16T20:55:06.805639688	2026-03-16T20:55:06.805639688	0	\N	\N	\N	\N	\N
11	7	13	18	1	\N	2026-03-18	08:40	09:00	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-16T21:23:46.798558427	2026-03-16T21:23:46.798558427	0	\N	\N	\N	\N	\N
12	7	13	18	1	\N	2026-03-18	08:20	08:40	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-16T21:25:37.044711745	2026-03-16T21:25:37.044711745	0	\N	\N	\N	\N	\N
13	7	13	18	1	\N	2026-03-27	08:20	08:40	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-28T17:42:41.863740071	2026-03-28T17:42:41.863740071	0	\N	\N	\N	\N	\N
14	7	13	18	1	\N	2026-03-27	08:40	09:00	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-03-28T17:43:00.861046596	2026-03-28T17:43:00.861046596	0	\N	\N	\N	\N	\N
15	2	13	18	1	\N	2026-03-23	10:20	10:40	VIRTUAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-04-06T19:49:09.999401935	2026-04-06T19:49:09.999401935	0	\N	\N	\N	\N	\N
16	1	13	18	1	\N	2026-04-11	09:00	09:20	PRESENCIAL	CONSULTA_PRIMERA_VEZ	1	Control Mensual		\N	PROGRAMADA	t	f	2026-04-06T20:06:31.730492589	2026-04-06T20:06:31.730492589	0	\N	\N	\N	\N	\N
\.


--
-- Data for Name: attribute_employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attribute_employee (id, employee_id, name_attribute, multiple) FROM stdin;
1	4	fecha de nacimiento	f
2	4	lugar de nacimiento ciudad	f
3	4	lugar de nacimiento departamento	f
4	4	lugar de nacimiento pais	f
5	4	ubicacion ciudad	f
6	4	ubicacion departamento	f
7	4	ubicacion pais	f
8	4	entidad de salud	f
9	4	ultima consulta	f
10	4	telefono	f
11	4	email	f
12	4	regimen	f
13	4	loginEnabled	f
14	2	fecha de nacimiento	f
15	2	lugar de nacimiento ciudad	f
16	2	lugar de nacimiento departamento	f
17	2	lugar de nacimiento pais	f
18	2	ubicacion ciudad	f
19	2	ubicacion departamento	f
20	2	ubicacion pais	f
21	2	entidad de salud	f
22	2	ultima consulta	f
23	2	telefono	f
24	2	email	f
25	2	regimen	f
26	2	loginEnabled	f
27	3	fecha de nacimiento	f
28	3	lugar de nacimiento ciudad	f
29	3	lugar de nacimiento departamento	f
30	3	lugar de nacimiento pais	f
31	3	ubicacion ciudad	f
32	3	ubicacion departamento	f
33	3	ubicacion pais	f
34	3	entidad de salud	f
35	3	ultima consulta	f
36	3	telefono	f
37	3	email	f
38	3	regimen	f
39	3	loginEnabled	f
40	5	fecha de nacimiento	f
41	5	lugar de nacimiento ciudad	f
42	5	lugar de nacimiento departamento	f
43	5	lugar de nacimiento pais	f
44	5	ubicacion ciudad	f
45	5	ubicacion departamento	f
46	5	ubicacion pais	f
47	5	entidad de salud	f
48	5	ultima consulta	f
49	5	telefono	f
50	5	email	f
51	5	regimen	f
52	5	loginEnabled	f
53	6	fecha de nacimiento	f
54	6	lugar de nacimiento ciudad	f
55	6	lugar de nacimiento departamento	f
56	6	lugar de nacimiento pais	f
57	6	ubicacion ciudad	f
58	6	ubicacion departamento	f
59	6	ubicacion pais	f
60	6	entidad de salud	f
61	6	ultima consulta	f
62	6	telefono	f
63	6	email	f
64	6	regimen	f
65	6	loginEnabled	f
66	1	fecha de nacimiento	f
67	1	lugar de nacimiento ciudad	f
68	1	lugar de nacimiento departamento	f
69	1	lugar de nacimiento pais	f
70	1	ubicacion ciudad	f
71	1	ubicacion departamento	f
72	1	ubicacion pais	f
73	1	entidad de salud	f
74	1	ultima consulta	f
75	1	telefono	f
76	1	email	f
77	1	regimen	f
78	1	loginEnabled	f
79	7	fecha de nacimiento	f
80	7	lugar de nacimiento ciudad	f
81	7	lugar de nacimiento departamento	f
82	7	lugar de nacimiento pais	f
83	7	ubicacion ciudad	f
84	7	ubicacion departamento	f
85	7	ubicacion pais	f
86	7	entidad de salud	f
87	7	ultima consulta	f
88	7	telefono	f
89	7	email	f
90	7	regimen	f
91	7	loginEnabled	f
92	8	fecha de nacimiento	f
93	8	lugar de nacimiento ciudad	f
94	8	lugar de nacimiento departamento	f
95	8	lugar de nacimiento pais	f
96	8	ubicacion ciudad	f
97	8	ubicacion departamento	f
98	8	ubicacion pais	f
99	8	entidad de salud	f
100	8	ultima consulta	f
101	8	telefono	f
102	8	email	f
103	8	regimen	f
104	8	loginEnabled	f
105	10	fecha de nacimiento	f
106	10	lugar de nacimiento ciudad	f
107	10	lugar de nacimiento departamento	f
108	10	lugar de nacimiento pais	f
109	10	ubicacion ciudad	f
110	10	ubicacion departamento	f
111	10	ubicacion pais	f
112	10	entidad de salud	f
113	10	ultima consulta	f
114	10	telefono	f
115	10	email	f
116	10	regimen	f
117	10	loginEnabled	f
118	11	fecha de nacimiento	f
119	11	lugar de nacimiento ciudad	f
120	11	lugar de nacimiento departamento	f
121	11	lugar de nacimiento pais	f
122	11	ubicacion ciudad	f
123	11	ubicacion departamento	f
124	11	ubicacion pais	f
125	11	entidad de salud	f
126	11	ultima consulta	f
127	11	telefono	f
128	11	email	f
129	11	regimen	f
130	11	loginEnabled	f
131	9	fecha de nacimiento	f
132	9	lugar de nacimiento ciudad	f
133	9	lugar de nacimiento departamento	f
134	9	lugar de nacimiento pais	f
135	9	ubicacion ciudad	f
136	9	ubicacion departamento	f
137	9	ubicacion pais	f
138	9	entidad de salud	f
139	9	ultima consulta	f
140	9	telefono	f
141	9	email	f
142	9	regimen	f
143	9	loginEnabled	f
144	12	email	f
145	12	loginEnabled	f
146	12	phone	f
147	12	address	f
148	12	medical_registry	f
149	12	specialty	f
150	12	sedes	f
151	13	email	f
152	13	loginEnabled	f
153	13	phone	f
154	13	address	f
155	13	medical_registry	f
156	13	specialty	f
157	13	sedes	f
\.


--
-- Data for Name: attribute_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attribute_user (id, user_id, name_attribute, multiple) FROM stdin;
1	2	fecha de nacimiento	f
2	2	lugar de nacimiento ciudad	f
3	2	lugar de nacimiento departamento	f
4	2	lugar de nacimiento pais	f
5	2	ubicacion ciudad	f
6	2	ubicacion departamento	f
7	2	ubicacion pais	f
8	2	entidad de salud	f
9	2	ultima consulta	f
10	2	telefono	f
11	2	email	f
12	2	regimen	f
13	2	historia_clinica_numero	f
14	2	diagnostico_principal	f
15	2	alergias	t
16	3	fecha de nacimiento	f
17	3	lugar de nacimiento ciudad	f
18	3	lugar de nacimiento departamento	f
19	3	lugar de nacimiento pais	f
20	3	ubicacion ciudad	f
21	3	ubicacion departamento	f
22	3	ubicacion pais	f
23	3	entidad de salud	f
24	3	ultima consulta	f
25	3	telefono	f
26	3	email	f
27	3	regimen	f
28	3	historia_clinica_numero	f
29	3	diagnostico_principal	f
30	3	alergias	t
31	4	fecha de nacimiento	f
32	4	lugar de nacimiento ciudad	f
33	4	lugar de nacimiento departamento	f
34	4	lugar de nacimiento pais	f
35	4	ubicacion ciudad	f
36	4	ubicacion departamento	f
37	4	ubicacion pais	f
38	4	entidad de salud	f
39	4	ultima consulta	f
40	4	telefono	f
41	4	email	f
42	4	regimen	f
43	4	historia_clinica_numero	f
44	4	diagnostico_principal	f
45	4	alergias	t
46	5	fecha de nacimiento	f
47	5	lugar de nacimiento ciudad	f
48	5	lugar de nacimiento departamento	f
49	5	lugar de nacimiento pais	f
50	5	ubicacion ciudad	f
51	5	ubicacion departamento	f
52	5	ubicacion pais	f
53	5	entidad de salud	f
54	5	ultima consulta	f
55	5	telefono	f
56	5	email	f
57	5	regimen	f
58	5	historia_clinica_numero	f
59	5	diagnostico_principal	f
60	5	alergias	t
61	6	fecha de nacimiento	f
62	6	lugar de nacimiento ciudad	f
63	6	lugar de nacimiento departamento	f
64	6	lugar de nacimiento pais	f
65	6	ubicacion ciudad	f
66	6	ubicacion departamento	f
67	6	ubicacion pais	f
68	6	entidad de salud	f
69	6	ultima consulta	f
70	6	telefono	f
71	6	email	f
72	6	regimen	f
73	6	historia_clinica_numero	f
74	6	diagnostico_principal	f
75	6	alergias	t
76	1	fecha de nacimiento	f
77	1	lugar de nacimiento ciudad	f
78	1	lugar de nacimiento departamento	f
79	1	lugar de nacimiento pais	f
80	1	ubicacion ciudad	f
81	1	ubicacion departamento	f
82	1	ubicacion pais	f
83	1	entidad de salud	f
84	1	ultima consulta	f
85	1	telefono	f
86	1	email	f
87	1	regimen	f
88	1	historia_clinica_numero	f
89	1	diagnostico_principal	f
90	1	alergias	t
91	7	fecha de nacimiento	f
92	7	lugar de nacimiento ciudad	f
93	7	lugar de nacimiento departamento	f
94	7	lugar de nacimiento pais	f
95	7	ubicacion ciudad	f
96	7	ubicacion departamento	f
97	7	ubicacion pais	f
98	7	entidad de salud	f
99	7	ultima consulta	f
100	7	telefono	f
101	7	email	f
102	7	regimen	f
103	7	historia_clinica_numero	f
104	7	diagnostico_principal	f
105	7	alergias	t
\.


--
-- Data for Name: calendar_exception; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.calendar_exception (id, employee_id, modality, headquarters_id, office_id, exception_date, start_time, end_time, is_full_day, reason, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: contratos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.contratos (id, eapb_id, nombre_contrato, regimen, modalidad_pago, objeto_contrato, fecha_inicio, fecha_fin, valor_total, estado, nivel_complejidad, id_contrato_legal, servicios_cubiertos, sedes_aplicables, observaciones, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: departamentos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.departamentos (id, nombre, codigo) FROM stdin;
\.


--
-- Data for Name: eapbs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.eapbs (id, nombre, nit, digito_verificacion, codigo_supersalud, regimen, naturaleza, estado, representante_legal, departamento_id, municipio_id, direccion, telefono, correo_electronico, id_interno_ese, observaciones, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (id, names, lastnames, identification_type, identification_number, password, rol_id, secret) FROM stdin;
1	Juan	Campo	CC	1	\N	\N	\N
2	Elieser	Banguero	CC	2	\N	\N	\N
3	Migel	Caicedo	CC	3	\N	\N	\N
4	Huber	Guaza	CC	4	\N	\N	\N
5	Kenner	Zambrano	CC	5	\N	\N	\N
6	Jhordy	Abonia	CC	7	$2a$10$/EV8DcpdCFYmKTCMouyt.ObIE1X1tOgSfpgQawvWmMq2WIvgyzs4i	1	\N
7	Yeider	Caicedo	CC	6	$2a$10$qUD.WWu1XMmfoSDUDrfmqeqgLZndxy6uyii2zvkXbCp3vDOw1PrIK	1	\N
8	Jhon	Doe 1	CC	8	\N	\N	\N
9	Jhon	Doe 2	CC	9	\N	\N	\N
10	Jhon	Doe 3	CC	10	\N	\N	\N
11	Jhon	Doe 4	CC	11	\N	\N	\N
12	Jhordy	Abonia	CC	888	$2a$10$5Jg.sHp56l3q1BVIuUUn3uFt4QBlWBtosE/YKWK712jOUn5pQfG36	1	\N
13	MEDICO	GENERAL	CC	777	$2a$10$p0ctRloV82gznqGQUaoLDOVWpBEqzPa3YvEsYPQ43HtYrI1EeWNj.	2	\N
\.


--
-- Data for Name: fb_attribute; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fb_attribute (id, code, label, input_type, is_required, placeholder, default_value, tooltip, validation_rules, options, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: fb_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fb_template (id, name, description, is_active, version, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: fb_template_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fb_template_group (id, template_id, name, description, sort_order, icon, is_collapsible) FROM stdin;
\.


--
-- Data for Name: fb_template_group_attr; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.fb_template_group_attr (id, group_id, attribute_id, sort_order, is_required_override, label_override, width) FROM stdin;
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1	<< Flyway Baseline >>	BASELINE	<< Flyway Baseline >>	\N	postgres	2026-02-16 12:19:40.507821	0	t
2	2	add asistencial to rol	SQL	V2__add_asistencial_to_rol.sql	-1026309532	postgres	2026-02-16 21:07:01.836259	6	t
\.


--
-- Data for Name: medical_agenda; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medical_agenda (id, employee_id, modality, headquarters_id, office_id, start_date, end_date, work_days, start_time, end_time, appointment_duration, service_types, allow_group_session, requires_referral, notes, status, is_active, created_at, updated_at, enabled, convenios, can_create_medical_history, double_shift, enabled_slots, agenda_state, frequency, created_by) FROM stdin;
9	7	intramural	1	101	2026-03-02	2026-03-27	L,M,X,J,V,S,D	08:00	17:00	20	2	f	f	Copia de: Copia de agenda	VIGENTE	t	2026-02-17 22:42:20.764548	2026-03-02 21:57:18.041355	t	\N	f	f	\N	ABIERTA	\N	\N
17	1	intramural	1	101	2026-03-02	2026-03-28	L,M,X,J,V	08:00	17:00	20	2	f	f	Copia de: Copia de agenda	VIGENTE	t	2026-03-02 21:12:35.758	2026-03-02 22:29:04.653711	t	\N	f	f	\N	ABIERTA	\N	\N
23	13	intramural	3	301	2026-03-01	2026-03-31	L,M,X,J,V	08:00	17:00	20	6	f	f	\N	INACTIVA	f	2026-03-16 21:20:52.091681	2026-03-16 21:21:53.0708	f	\N	f	f	\N	ABIERTA	\N	\N
18	13	intramural	1	101	2026-03-01	2026-06-29	L,M,X,J,V	08:00	17:00	20	1	f	f	\N	VIGENTE	t	2026-03-07 15:41:36.457394	2026-04-06 20:05:29.770668	t	\N	f	f	\N	ABIERTA	\N	\N
\.


--
-- Data for Name: municipios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.municipios (id, nombre, codigo, departamento_id) FROM stdin;
\.


--
-- Data for Name: permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permission (id, rol_id, method, endpoint) FROM stdin;
1	1	GET	api/v1/tracking
2	1	GET	/api/v1/schedule
3	1	PUT	/api/v1/schedule
4	1	POST	/api/v1/schedule
5	1	DELETE	/api/v1/schedule
6	1	GET	/api/v1/medical-agenda
7	1	PUT	/api/v1/medical-agenda
8	1	PATCH	/api/v1/medical-agenda
9	1	POST	/api/v1/medical-agenda
10	1	DELETE	/api/v1/medical-agenda
11	1	GET	/api/v1/appointments
12	1	PUT	/api/v1/appointments
13	1	POST	/api/v1/appointments
14	1	DELETE	/api/v1/appointments
15	1	GET	/api/v1/rols
16	1	PUT	/api/v1/rols
17	1	POST	/api/v1/rols
18	1	DELETE	/api/v1/rols
19	1	GET	/api/v1/employees
20	1	PUT	/api/v1/employees
21	1	PATCH	/api/v1/employees
22	1	POST	/api/v1/employees
23	1	DELETE	/api/v1/employees
24	1	GET	/api/v1/users
25	1	PUT	/api/v1/users
26	1	PATCH	/api/v1/users
27	1	POST	/api/v1/users
28	1	DELETE	/api/v1/users
29	2	GET	/api/v1/users
30	2	PATCH	/api/v1/users
31	2	GET	/api/v1/schedule/employee/{employeeId}
32	1	GET	/api/v1/convenios/contratos
33	1	GET	/api/v1/convenios/eapbs
\.


--
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id, name, asistencial) FROM stdin;
1	ADMIN	f
2	DOCTOR	t
\.


--
-- Data for Name: schedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schedule (id, employee_id, user_id, start_at, end_at, details, group_session, created_at, updated_at, headquarters, office, in_person, office_id, agenda_id) FROM stdin;
2	1	11	2025-12-04 14:00:00	2025-12-04 15:30:00	Control médico - Empleado 1	f	2025-12-03 22:22:15.087733	2025-12-03 22:22:15.087742	\N	\N	f	\N	\N
3	1	21	2025-12-04 16:00:00	2025-12-04 16:45:00	Procedimiento especializado - Empleado 1	f	2025-12-03 22:22:15.087773	2025-12-03 22:22:15.087781	\N	\N	f	\N	\N
4	2	2	2025-12-05 09:00:00	2025-12-05 10:00:00	Consulta general - Empleado 2	f	2025-12-03 22:22:15.087809	2025-12-03 22:22:15.087817	\N	\N	f	\N	\N
5	2	12	2025-12-05 14:00:00	2025-12-05 15:30:00	Control médico - Empleado 2	f	2025-12-03 22:22:15.087851	2025-12-03 22:22:15.08786	\N	\N	f	\N	\N
6	2	22	2025-12-05 16:00:00	2025-12-05 16:45:00	Procedimiento especializado - Empleado 2	f	2025-12-03 22:22:15.087933	2025-12-03 22:22:15.087944	\N	\N	f	\N	\N
7	3	3	2025-12-06 09:00:00	2025-12-06 10:00:00	Consulta general - Empleado 3	f	2025-12-03 22:22:15.088004	2025-12-03 22:22:15.088013	\N	\N	f	\N	\N
8	3	13	2025-12-06 14:00:00	2025-12-06 15:30:00	Control médico - Empleado 3	f	2025-12-03 22:22:15.088058	2025-12-03 22:22:15.088066	\N	\N	f	\N	\N
9	3	23	2025-12-06 16:00:00	2025-12-06 16:45:00	Procedimiento especializado - Empleado 3	f	2025-12-03 22:22:15.088126	2025-12-03 22:22:15.088148	\N	\N	f	\N	\N
10	4	4	2025-12-07 09:00:00	2025-12-07 10:00:00	Consulta general - Empleado 4	f	2025-12-03 22:22:15.08818	2025-12-03 22:22:15.08819	\N	\N	f	\N	\N
11	4	14	2025-12-07 14:00:00	2025-12-07 15:30:00	Control médico - Empleado 4	f	2025-12-03 22:22:15.088221	2025-12-03 22:22:15.088229	\N	\N	f	\N	\N
12	4	24	2025-12-07 16:00:00	2025-12-07 16:45:00	Procedimiento especializado - Empleado 4	f	2025-12-03 22:22:15.08826	2025-12-03 22:22:15.088268	\N	\N	f	\N	\N
13	5	5	2025-12-08 09:00:00	2025-12-08 10:00:00	Consulta general - Empleado 5	f	2025-12-03 22:22:15.088296	2025-12-03 22:22:15.088304	\N	\N	f	\N	\N
14	5	15	2025-12-08 14:00:00	2025-12-08 15:30:00	Control médico - Empleado 5	f	2025-12-03 22:22:15.088356	2025-12-03 22:22:15.088367	\N	\N	f	\N	\N
15	6	6	2025-12-09 09:00:00	2025-12-09 10:00:00	Consulta general - Empleado 6	f	2025-12-03 22:22:15.088396	2025-12-03 22:22:15.088405	\N	\N	f	\N	\N
16	6	16	2025-12-09 14:00:00	2025-12-09 15:30:00	Control médico - Empleado 6	f	2025-12-03 22:22:15.08844	2025-12-03 22:22:15.088448	\N	\N	f	\N	\N
17	7	7	2025-12-10 09:00:00	2025-12-10 10:00:00	Consulta general - Empleado 7	f	2025-12-03 22:22:15.088479	2025-12-03 22:22:15.088489	\N	\N	f	\N	\N
18	7	17	2025-12-10 14:00:00	2025-12-10 15:30:00	Control médico - Empleado 7	f	2025-12-03 22:22:15.088519	2025-12-03 22:22:15.088528	\N	\N	f	\N	\N
19	1	31	2025-12-11 10:00:00	2025-12-11 12:00:00	Cita de seguimiento semanal - Empleado 1	f	2025-12-03 22:22:15.088565	2025-12-03 22:22:15.088574	\N	\N	f	\N	\N
20	2	32	2025-12-12 10:00:00	2025-12-12 12:00:00	Cita de seguimiento semanal - Empleado 2	f	2025-12-03 22:22:15.088602	2025-12-03 22:22:15.088611	\N	\N	f	\N	\N
21	3	33	2025-12-13 10:00:00	2025-12-13 12:00:00	Cita de seguimiento semanal - Empleado 3	f	2025-12-03 22:22:15.088639	2025-12-03 22:22:15.088648	\N	\N	f	\N	\N
22	4	34	2025-12-14 10:00:00	2025-12-14 12:00:00	Cita de seguimiento semanal - Empleado 4	f	2025-12-03 22:22:15.088678	2025-12-03 22:22:15.088689	\N	\N	f	\N	\N
23	5	35	2025-12-15 10:00:00	2025-12-15 12:00:00	Cita de seguimiento semanal - Empleado 5	f	2025-12-03 22:22:15.088717	2025-12-03 22:22:15.088726	\N	\N	f	\N	\N
24	1	100	2025-12-06 16:00:00	2025-12-06 17:00:00	Terapia grupal - Manejo del estrés	t	2025-12-03 22:22:15.088741	2025-12-03 22:22:15.088747	\N	\N	f	\N	\N
25	1	101	2025-12-06 16:00:00	2025-12-06 17:00:00	Terapia grupal - Manejo del estrés	t	2025-12-03 22:22:15.088753	2025-12-03 22:22:15.08878	\N	\N	f	\N	\N
26	1	102	2025-12-06 16:00:00	2025-12-06 17:00:00	Terapia grupal - Manejo del estrés	t	2025-12-03 22:22:15.088787	2025-12-03 22:22:15.088866	\N	\N	f	\N	\N
27	2	103	2025-12-07 11:00:00	2025-12-07 12:30:00	Sesión educativa - Nutrición saludable	t	2025-12-03 22:22:15.088889	2025-12-03 22:22:15.088913	\N	\N	f	\N	\N
28	2	104	2025-12-07 11:00:00	2025-12-07 12:30:00	Sesión educativa - Nutrición saludable	t	2025-12-03 22:22:15.088921	2025-12-03 22:22:15.088927	\N	\N	f	\N	\N
29	3	105	2025-12-09 08:00:00	2025-12-09 08:45:00	Clase grupal de ejercicios terapéuticos	t	2025-12-03 22:22:15.08894	2025-12-03 22:22:15.088947	\N	\N	f	\N	\N
30	3	106	2025-12-09 08:00:00	2025-12-09 08:45:00	Clase grupal de ejercicios terapéuticos	t	2025-12-03 22:22:15.088952	2025-12-03 22:22:15.088957	\N	\N	f	\N	\N
31	3	107	2025-12-09 08:00:00	2025-12-09 08:45:00	Clase grupal de ejercicios terapéuticos	t	2025-12-03 22:22:15.088961	2025-12-03 22:22:15.088965	\N	\N	f	\N	\N
32	3	108	2025-12-09 08:00:00	2025-12-09 08:45:00	Clase grupal de ejercicios terapéuticos	t	2025-12-03 22:22:15.08897	2025-12-03 22:22:15.088975	\N	\N	f	\N	\N
33	1	1	2025-12-31 13:00:00	2025-12-31 17:00:00	Consulta con Dr. Carlos Rivera	f	2025-12-31 14:30:04.787227	2025-12-31 14:30:04.787251	\N	\N	f	\N	\N
34	3	1	2026-01-01 13:00:00	2026-01-01 17:00:00	Consulta con Dr. Javier López	f	2025-12-31 14:32:43.529416	2025-12-31 14:32:43.529429	\N	\N	f	\N	\N
35	3	1	2026-01-02 13:00:00	2026-01-02 17:00:00	no se tu dime	f	2025-12-31 14:33:55.325886	2025-12-31 14:33:55.325901	\N	\N	f	\N	\N
36	1	1	2025-12-31 19:23:06.091	2025-12-31 19:23:06.091	Consulta médica general	f	2025-12-31 15:16:31.164531	2025-12-31 15:16:31.164549	\N	\N	f	\N	\N
37	1	1	2026-12-31 19:23:06.091	2026-12-31 19:23:06.091	Consulta médica general	f	2025-12-31 15:26:25.10632	2025-12-31 15:26:25.106332	\N	\N	f	\N	\N
38	3	5	2026-02-01 13:00:00	2026-02-01 17:00:00	Consulta con Dra. Ana María Torres	t	2025-12-31 15:29:12.999248	2025-12-31 15:29:12.999258	\N	\N	f	\N	\N
39	3	5	2026-02-01 13:00:00	2026-02-01 17:00:00	Consulta con Dra. Ana María Torres	t	2025-12-31 15:29:17.097616	2025-12-31 15:29:17.097628	\N	\N	f	\N	\N
40	3	5	2026-02-01 13:00:00	2026-02-01 17:00:00	Consulta con Dra. Ana María Torres	t	2025-12-31 15:29:18.425151	2025-12-31 15:29:18.425162	\N	\N	f	\N	\N
41	3	5	2026-02-01 13:00:00	2026-02-01 17:00:00	Consulta con Dra. Ana María Torres	t	2025-12-31 15:29:19.565735	2025-12-31 15:29:19.565746	\N	\N	f	\N	\N
42	3	5	2026-02-01 13:00:00	2026-02-01 17:00:00	Consulta con Dra. Ana María Torres	t	2025-12-31 15:29:20.560894	2025-12-31 15:29:20.560907	\N	\N	f	\N	\N
43	3	5	2026-02-01 13:00:00	2026-02-01 17:00:00	Consulta con Dra. Ana María Torres	t	2025-12-31 15:29:27.533555	2025-12-31 15:29:27.533566	\N	\N	f	\N	\N
44	3	5	2026-02-01 13:00:00	2026-02-01 17:00:00	Consulta con Dra. Ana María Torres	t	2025-12-31 15:29:28.557291	2025-12-31 15:29:28.557301	\N	\N	f	\N	\N
45	3	5	2026-03-01 13:00:00	2026-03-01 17:00:00	Consulta con Dra. Ana María Torres	f	2025-12-31 15:29:49.85941	2025-12-31 15:29:49.85942	\N	\N	f	\N	\N
46	2	1	2026-01-23 13:00:00	2026-01-23 17:00:00	Consulta con Dra. Ana María Torres	f	2025-12-31 15:30:03.449728	2025-12-31 15:30:03.449751	\N	\N	f	\N	\N
47	7	2	2025-12-31 13:00:00	2025-12-31 17:00:00	Consulta con Jhordy Abonia	f	2025-12-31 16:26:39.05186	2025-12-31 16:26:39.051867	\N	\N	f	\N	\N
1	1	1	2025-12-04 09:00:00	2025-12-04 10:00:00	Consulta general - Empleado 1	f	2025-12-03 22:22:15.087673	2025-12-03 22:22:15.087684	\N	\N	f	1	2
\.


--
-- Data for Name: schedule_config; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schedule_config (id, config_type, holiday_date, description, created_at) FROM stdin;
\.


--
-- Data for Name: session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.session (id, user_id, token, ip_address, useragent, created_at, expiration) FROM stdin;
\.


--
-- Data for Name: tracking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tracking (id, created_at, employee_id, action, data, result) FROM stdin;
1	2026-03-30 20:46:12.199627	1	/auth/login	{"username": "admin", "password": "***"}	{"status": "success", "token": "jwt123..."}
2	2026-03-30 21:46:12.199627	2	/api/v1/schedule	{"employeeId": 1, "userId": 100, "startAt": "2024-12-02T09:00:00"}	{"status": "created", "id": 1}
3	2026-03-30 22:46:12.199627	1	auth: login_attempt	{"username": "admin", "ip": "192.168.1.100"}	{"status": "success"}
4	2026-03-30 23:46:12.199627	3	auth: logout	{"session_id": "sess123"}	{"status": "success"}
5	2026-03-31 00:46:12.199627	\N	error: validation_error	{"field": "email", "message": "Invalid format"}	ValidationException: Email format is invalid
6	2026-03-31 01:46:12.199627	1	/api/v1/users	{}	{"data": [...], "total": 25}
7	2026-03-31 02:46:12.199627	2	/api/v1/employees	{"page": 0, "size": 10}	{"content": [...], "totalElements": 15}
8	2026-03-31 03:46:12.199627	\N	system: startup	{"module": "gateway", "port": 8080}	{"status": "started", "uptime": 0}
9	2026-03-31 04:46:12.199627	4	/tracking/latest	{"limit": 50}	{"count": 8}
10	2026-03-31 05:46:12.199627	1	/api/v1/schedule	{"employeeId": 1, "userId": 101, "groupSession": true, "startAt": "2024-12-02T16:00:00", "endAt": "2024-12-02T17:00:00"}	{"status": "created", "id": 15, "groupSession": true}
11	2026-04-06 19:47:50.276951	\N	POST /api/v1/auth/login	{***}	status=200
12	2026-04-06 19:49:10.030823	6	POST /api/v1/appointments	{"patientId":2,"professionalId":13,"agendaId":18,"headquartersId":1,"date":"2026-03-23","startTime":"10:20","modality":"VIRTUAL","functionality":"CONSULTA_PRIMERA_VEZ","serviceTypeId":1,"label":"Control Mensual","administrativeNotes":"","isGroupSession":false,"autoNotificationEnabled":true}	status=200
13	2026-04-06 20:05:29.79913	6	PATCH /api/v1/medical-agenda/18	{"employeeId":13,"modality":"intramural","headquartersId":1,"officeId":101,"startDate":"2026-03-01","endDate":"2026-06-29","workDays":"L,M,X,J,V","startTime":"08:00","endTime":"17:00","appointmentDuration":20,"serviceTypeIds":[1],"allowGroupSession":false,"requiresReferral":false,"enabled":true,"convenioIds":[],"agendaState":"ABIERTA"}	status=200
14	2026-04-06 20:06:31.740222	6	POST /api/v1/appointments	{"patientId":1,"professionalId":13,"agendaId":18,"headquartersId":1,"date":"2026-04-11","startTime":"09:00","modality":"PRESENCIAL","functionality":"CONSULTA_PRIMERA_VEZ","serviceTypeId":1,"label":"Control Mensual","administrativeNotes":"","isGroupSession":false,"autoNotificationEnabled":true}	status=200
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, names, lastnames, identification_type, identification_number) FROM stdin;
1	Juan	Campo	CC	1
2	Elieser	Banguero	CC	2
3	Migel	Caicedo	CC	3
4	Huber	Guaza	CC	4
5	Kenner	Zambrano	CC	5
6	Yeider	Caicedo	CC	6
7	Jhordy	Abonia	CC	7
\.


--
-- Data for Name: value_attribute_employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.value_attribute_employee (id, attribute_id, value_attribute) FROM stdin;
1	2	cali
2	5	guachene
3	8	sura
4	6	cauca
5	4	colombia
6	3	valle
7	9	2024-06-06
8	1	1992-05-06
9	10	315-000-0000
10	15	cali
11	7	colombia
12	18	guachene
13	12	
14	23	315-000-0000
15	22	2024-06-06
16	20	colombia
17	24	jhon-doe@test.co
18	16	valle
19	17	colombia
21	32	cauca
20	21	sura
22	25	
23	33	colombia
24	14	1992-05-06
25	13	true
26	31	guachene
27	11	jhon-doe@test.co
28	19	cauca
29	28	cali
30	30	colombia
31	29	valle
32	26	true
33	27	1992-05-06
34	40	1992-05-06
35	38	
36	36	315-000-0000
37	35	2024-06-06
38	39	true
39	43	colombia
40	42	valle
41	48	2024-06-06
42	37	jhon-doe@test.co
43	41	cali
44	50	jhon-doe@test.co
45	51	
46	44	guachene
47	52	true
48	46	colombia
49	57	guachene
50	49	315-000-0000
51	60	sura
52	47	sura
53	56	colombia
54	45	cauca
55	54	cali
56	59	colombia
57	58	cauca
58	55	valle
59	64	
60	53	1992-05-06
61	67	cali
62	68	valle
63	66	1992-05-06
64	63	jhon-doe@test.co
65	65	true
66	62	315-000-0000
67	70	guachene
68	71	cauca
69	61	2024-06-06
70	72	colombia
71	73	sura
72	77	
73	74	2024-06-06
74	75	315-000-0000
75	79	1992-05-06
76	80	cali
77	69	colombia
78	76	jhon-doe@test.co
79	84	cauca
80	85	colombia
81	86	sura
82	87	2024-06-06
83	78	true
84	81	valle
85	82	colombia
86	83	guachene
87	89	jhon-doe@test.co
88	90	
89	91	true
90	92	1992-05-06
91	94	valle
92	93	cali
93	88	315-000-0000
94	97	cauca
95	96	guachene
96	95	colombia
97	101	315-000-0000
98	99	sura
99	102	jhon-doe@test.co
100	100	2024-06-06
101	98	colombia
102	105	1992-05-06
103	103	
104	106	cali
105	107	valle
106	104	true
107	108	colombia
108	110	cauca
109	111	colombia
110	109	guachene
111	114	315-000-0000
112	112	sura
113	115	jhon-doe@test.co
114	113	2024-06-06
115	116	
116	117	true
117	120	valle
118	121	colombia
119	119	cali
120	123	cauca
121	118	1992-05-06
122	124	colombia
123	125	sura
124	129	
125	126	2024-06-06
126	127	315-000-0000
127	128	jhon-doe@test.co
128	130	true
129	122	guachene
130	131	1992-05-06
131	133	valle
132	134	colombia
133	132	cali
134	135	guachene
135	136	cauca
136	137	colombia
137	138	sura
138	139	2024-06-06
139	140	315-000-0000
140	143	true
141	142	
142	141	jhon-doe@test.co
143	34	sura
144	144	jhordy.abonia@gmail.com
145	145	false
146	146	123456789
147	147	carrera 7a # 8-39, Guchené, Cauca
148	150	1
149	151	jhordy.abonia+1@gmail.com
150	152	true
151	153	123456789
152	154	carrera 7a # 8-39, Guchené, Cauca
153	155	135
154	156	CIRUGIA
\.


--
-- Data for Name: value_attribute_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.value_attribute_user (id, attribute_id, value_attribute) FROM stdin;
1	15	Ninguna
2	30	Ninguna
3	45	Ninguna
4	60	Ninguna
5	75	Ninguna
6	90	Ninguna
7	105	Ninguna
8	6	cauca
9	8	sura
10	7	colombia
11	5	guachene
12	2	cali
13	3	valle
14	10	315-000-0000
15	9	2024-06-06
16	4	colombia
17	19	colombia
18	1	1992-05-06
19	14	Hipertension
20	17	cali
21	13	HC-100013
22	18	valle
23	11	jhon-doe@test.co
24	16	1992-05-06
25	23	sura
26	22	colombia
27	20	guachene
28	24	2024-06-06
29	12	subcidiado
30	27	subcidiado
31	26	jhon-doe@test.co
32	31	1992-05-06
33	28	HC-100028
34	25	315-000-0000
35	32	cali
36	34	colombia
37	37	colombia
38	36	cauca
39	29	Hipertension
40	35	guachene
41	39	2024-06-06
42	33	valle
43	40	315-000-0000
44	38	sura
45	42	subcidiado
46	41	jhon-doe@test.co
47	43	HC-100043
48	44	Hipertension
49	47	cali
50	48	valle
51	49	colombia
52	46	1992-05-06
53	51	cauca
54	53	sura
55	50	guachene
56	55	315-000-0000
57	56	jhon-doe@test.co
58	52	colombia
59	57	subcidiado
60	58	HC-100058
61	59	Hipertension
62	62	cali
63	63	valle
64	65	guachene
65	54	2024-06-06
66	61	1992-05-06
67	66	cauca
68	68	sura
69	69	2024-06-06
70	70	315-000-0000
71	71	jhon-doe@test.co
72	72	subcidiado
73	67	colombia
74	73	HC-100073
75	74	Hipertension
76	76	1992-05-06
77	64	colombia
78	77	cali
79	78	valle
80	80	guachene
81	81	cauca
82	82	colombia
83	83	sura
84	85	315-000-0000
85	86	jhon-doe@test.co
86	84	2024-06-06
87	87	subcidiado
88	88	HC-100088
89	79	colombia
90	89	Hipertension
91	91	1992-05-06
92	92	cali
93	93	valle
94	94	colombia
95	95	guachene
96	96	cauca
97	97	colombia
98	98	sura
99	99	2024-06-06
100	100	315-000-0000
101	101	jhon-doe@test.co
102	103	HC-1000103
103	104	Hipertension
104	102	subcidiado
105	21	cauca
\.


--
-- Name: appointment_notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointment_notifications_id_seq', 1, false);


--
-- Name: appointments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_id_seq', 16, true);


--
-- Name: attribute_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attribute_employee_id_seq', 157, true);


--
-- Name: attribute_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attribute_user_id_seq', 105, true);


--
-- Name: calendar_exception_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.calendar_exception_id_seq', 1, false);


--
-- Name: contratos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.contratos_id_seq', 1, false);


--
-- Name: departamentos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.departamentos_id_seq', 1, false);


--
-- Name: eapbs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.eapbs_id_seq', 1, false);


--
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_id_seq', 13, true);


--
-- Name: fb_attribute_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fb_attribute_id_seq', 1, false);


--
-- Name: fb_template_group_attr_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fb_template_group_attr_id_seq', 1, false);


--
-- Name: fb_template_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fb_template_group_id_seq', 1, false);


--
-- Name: fb_template_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fb_template_id_seq', 1, false);


--
-- Name: medical_agenda_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medical_agenda_id_seq', 23, true);


--
-- Name: municipios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.municipios_id_seq', 1, false);


--
-- Name: permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permission_id_seq', 33, true);


--
-- Name: rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_seq', 2, true);


--
-- Name: schedule_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.schedule_config_id_seq', 1, false);


--
-- Name: schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.schedule_id_seq', 47, true);


--
-- Name: session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.session_id_seq', 1, false);


--
-- Name: tracking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tracking_id_seq', 14, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- Name: value_attribute_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.value_attribute_employee_id_seq', 154, true);


--
-- Name: value_attribute_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.value_attribute_user_id_seq', 105, true);


--
-- Name: appointment_notifications appointment_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointment_notifications
    ADD CONSTRAINT appointment_notifications_pkey PRIMARY KEY (id);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: attribute_employee attribute_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_employee
    ADD CONSTRAINT attribute_employee_pkey PRIMARY KEY (id);


--
-- Name: attribute_user attribute_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_user
    ADD CONSTRAINT attribute_user_pkey PRIMARY KEY (id);


--
-- Name: calendar_exception calendar_exception_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_exception
    ADD CONSTRAINT calendar_exception_pkey PRIMARY KEY (id);


--
-- Name: contratos contratos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT contratos_pkey PRIMARY KEY (id);


--
-- Name: departamentos departamentos_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_codigo_key UNIQUE (codigo);


--
-- Name: departamentos departamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_pkey PRIMARY KEY (id);


--
-- Name: eapbs eapbs_codigo_supersalud_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eapbs
    ADD CONSTRAINT eapbs_codigo_supersalud_key UNIQUE (codigo_supersalud);


--
-- Name: eapbs eapbs_nit_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eapbs
    ADD CONSTRAINT eapbs_nit_key UNIQUE (nit);


--
-- Name: eapbs eapbs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eapbs
    ADD CONSTRAINT eapbs_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: fb_attribute fb_attribute_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_attribute
    ADD CONSTRAINT fb_attribute_code_key UNIQUE (code);


--
-- Name: fb_attribute fb_attribute_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_attribute
    ADD CONSTRAINT fb_attribute_pkey PRIMARY KEY (id);


--
-- Name: fb_template_group_attr fb_template_group_attr_group_id_attribute_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group_attr
    ADD CONSTRAINT fb_template_group_attr_group_id_attribute_id_key UNIQUE (group_id, attribute_id);


--
-- Name: fb_template_group_attr fb_template_group_attr_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group_attr
    ADD CONSTRAINT fb_template_group_attr_pkey PRIMARY KEY (id);


--
-- Name: fb_template_group fb_template_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group
    ADD CONSTRAINT fb_template_group_pkey PRIMARY KEY (id);


--
-- Name: fb_template fb_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template
    ADD CONSTRAINT fb_template_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: medical_agenda medical_agenda_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medical_agenda
    ADD CONSTRAINT medical_agenda_pkey PRIMARY KEY (id);


--
-- Name: municipios municipios_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipios
    ADD CONSTRAINT municipios_codigo_key UNIQUE (codigo);


--
-- Name: municipios municipios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipios
    ADD CONSTRAINT municipios_pkey PRIMARY KEY (id);


--
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (id);


--
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id);


--
-- Name: schedule_config schedule_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedule_config
    ADD CONSTRAINT schedule_config_pkey PRIMARY KEY (id);


--
-- Name: schedule schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT schedule_pkey PRIMARY KEY (id);


--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- Name: tracking tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tracking
    ADD CONSTRAINT tracking_pkey PRIMARY KEY (id);


--
-- Name: attribute_employee uq_employee_attribute; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_employee
    ADD CONSTRAINT uq_employee_attribute UNIQUE (employee_id, name_attribute);


--
-- Name: employees uq_employees_identification; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT uq_employees_identification UNIQUE (identification_type, identification_number);


--
-- Name: permission uq_permission; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT uq_permission UNIQUE (rol_id, method, endpoint);


--
-- Name: rol uq_rol_name; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT uq_rol_name UNIQUE (name);


--
-- Name: session uq_session_token; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT uq_session_token UNIQUE (token);


--
-- Name: session uq_session_user_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT uq_session_user_id UNIQUE (user_id);


--
-- Name: attribute_user uq_users_attribute; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attribute_user
    ADD CONSTRAINT uq_users_attribute UNIQUE (user_id, name_attribute);


--
-- Name: users uq_users_identification; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uq_users_identification UNIQUE (identification_type, identification_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: value_attribute_employee value_attribute_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.value_attribute_employee
    ADD CONSTRAINT value_attribute_employee_pkey PRIMARY KEY (id);


--
-- Name: value_attribute_user value_attribute_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.value_attribute_user
    ADD CONSTRAINT value_attribute_user_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_appointments_agenda_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_appointments_agenda_date ON public.appointments USING btree (agenda_id, date);


--
-- Name: idx_appointments_date_range; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_appointments_date_range ON public.appointments USING btree (date);


--
-- Name: idx_appointments_patient; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_appointments_patient ON public.appointments USING btree (patient_id, date);


--
-- Name: idx_appointments_slot; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_appointments_slot ON public.appointments USING btree (professional_id, agenda_id, date, start_time);


--
-- Name: idx_appointments_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_appointments_status ON public.appointments USING btree (status, date);


--
-- Name: idx_cal_exception_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cal_exception_date ON public.calendar_exception USING btree (exception_date);


--
-- Name: idx_cal_exception_employee; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_cal_exception_employee ON public.calendar_exception USING btree (employee_id);


--
-- Name: idx_contratos_eapb_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_contratos_eapb_id ON public.contratos USING btree (eapb_id);


--
-- Name: idx_contratos_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_contratos_estado ON public.contratos USING btree (estado);


--
-- Name: idx_contratos_fecha_fin; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_contratos_fecha_fin ON public.contratos USING btree (fecha_fin);


--
-- Name: idx_eapbs_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_eapbs_estado ON public.eapbs USING btree (estado);


--
-- Name: idx_eapbs_nombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_eapbs_nombre ON public.eapbs USING btree (nombre);


--
-- Name: idx_eapbs_regimen; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_eapbs_regimen ON public.eapbs USING btree (regimen);


--
-- Name: idx_med_agenda_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_med_agenda_active ON public.medical_agenda USING btree (is_active);


--
-- Name: idx_med_agenda_employee; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_med_agenda_employee ON public.medical_agenda USING btree (employee_id);


--
-- Name: idx_med_agenda_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_med_agenda_status ON public.medical_agenda USING btree (status);


--
-- Name: idx_schedule_employee_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_schedule_employee_id ON public.schedule USING btree (employee_id);


--
-- Name: idx_schedule_end_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_schedule_end_at ON public.schedule USING btree (end_at);


--
-- Name: idx_schedule_start_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_schedule_start_at ON public.schedule USING btree (start_at);


--
-- Name: idx_schedule_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_schedule_user_id ON public.schedule USING btree (user_id);


--
-- Name: idx_tg_template; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tg_template ON public.fb_template_group USING btree (template_id);


--
-- Name: idx_tga_attribute; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tga_attribute ON public.fb_template_group_attr USING btree (attribute_id);


--
-- Name: idx_tga_group; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_tga_group ON public.fb_template_group_attr USING btree (group_id);


--
-- Name: contratos contratos_eapb_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contratos
    ADD CONSTRAINT contratos_eapb_id_fkey FOREIGN KEY (eapb_id) REFERENCES public.eapbs(id);


--
-- Name: eapbs eapbs_departamento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eapbs
    ADD CONSTRAINT eapbs_departamento_id_fkey FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id);


--
-- Name: eapbs eapbs_municipio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eapbs
    ADD CONSTRAINT eapbs_municipio_id_fkey FOREIGN KEY (municipio_id) REFERENCES public.municipios(id);


--
-- Name: fb_template_group_attr fb_template_group_attr_attribute_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group_attr
    ADD CONSTRAINT fb_template_group_attr_attribute_id_fkey FOREIGN KEY (attribute_id) REFERENCES public.fb_attribute(id) ON DELETE RESTRICT;


--
-- Name: fb_template_group_attr fb_template_group_attr_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group_attr
    ADD CONSTRAINT fb_template_group_attr_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.fb_template_group(id) ON DELETE CASCADE;


--
-- Name: fb_template_group fb_template_group_template_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fb_template_group
    ADD CONSTRAINT fb_template_group_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.fb_template(id) ON DELETE CASCADE;


--
-- Name: employees fk_employees_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_employees_rol FOREIGN KEY (rol_id) REFERENCES public.rol(id);


--
-- Name: permission fk_permission_rol; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT fk_permission_rol FOREIGN KEY (rol_id) REFERENCES public.rol(id);


--
-- Name: municipios municipios_departamento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipios
    ADD CONSTRAINT municipios_departamento_id_fkey FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id);


--
-- PostgreSQL database dump complete
--

\unrestrict wa9yUNddJEMKxvYskzuBkxgjdpPscav8NoUtFz3ecQeDvuaIihpZ4pmLogIlT9P

